import { ReactElement, useEffect } from "react";
import type { NextPageWithLayout } from "./_app";
import Head from "next/head";
import MainLayout from "@/components/Layouts/MainLayout";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
// import Login from "@/components/Authentication/Login";
// import Signup from "@/components/Authentication/Signup";

const HomePage: NextPageWithLayout = () => {
  const router = useRouter();

  useEffect(() => {
    // @ts-ignore
    const user = JSON.parse(localStorage.getItem("userInfo"));

    if (user) router.push("/chats");
  }, [router.route]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex h-[80vh] flex-col items-center justify-center">
        <Link href="/auth">
          <Image
            src="/logo.webp"
            alt="logo"
            priority
            width={573}
            height={573}
            quality={100}
            className="animate-pulse p-6"
          />
        </Link>
        <h1 className="font-Goldman text-5xl drop-shadow-3xl">StealthTalk</h1>
      </section>
    </>
  );
};

HomePage.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>;

export default HomePage;
